{% set name = "mandrake" %}
{% set version = "1.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bacpop/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: a21a05dba9964d99c6494c05e719e9c05747cea7f8b9c60bbcd1d4b330c1fef4
  patches:
    - non-x86_64.patch  # [aarch64 or ppc64le]
    - find_python-non-linux64.patch  # [not linux64]

build:
  number: 0
  skip: true  # [py<38 or win or cuda_compiler_version in ("9.2", "10.0", "10.1", "10.2", "11.0")]
  script:
    - export SCE_BUILD_ENV="conda_forge"  # [cuda_compiler_version == "None"]
    - export SCE_BUILD_ENV="conda_forge_cuda"  # [linux64 and cuda_compiler_version != "None"]
    - export GENARCH="-gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_86,code=sm_86"  # [cuda_compiler_version != "None"]
    - export GENARCH="$GENARCH -gencode arch=compute_90,code=sm_90"  # [(cuda_compiler_version or "").startswith("12")]
    - {{ PYTHON }} -m pip install . -vv
  missing_dso_whitelist:
    - '*/libcuda.*'
  ignore_run_exports:
    - cudatoolkit
  entry_points:
    - mandrake = mandrake.__main__:main

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [linux64 and cuda_compiler_version != "None"]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11 >=2.12.0                      # [build_platform != target_platform]
    - cmake >=3.19
    - make
  host:
    - cuda-version {{ cuda_compiler_version }}  # [(cuda_compiler_version or "None") != "None"]
    - python
    - setuptools
    - pip
    - pybind11
    - zlib
    - libboost-devel
    - cuda-profiler-api  # [(cuda_compiler_version or "").startswith("12")]
    - llvm-openmp        # [osx]
    - libgomp            # [linux64]
  run:
    - python
    - zlib
    - numpy
    - scipy
    - scikit-learn
    - pandas
    - plotly
    - matplotlib-base
    - hdbscan
    - pp-sketchlib >=2.0.0
    - hdf5
    - h5py
    - tqdm
    - ffmpeg

test:
  imports:
    - SCE
  commands:
    - mandrake --version

about:
  home: https://github.com/bacpop/mandrake
  license: Apache-2.0 AND MIT
  license_file:
    - NOTICE
    - LICENSE
    - LICENSE_kseq
  summary: Stochastic cluster embedding with genetic distances
  doc_url: https://mandrake.readthedocs.io/en/latest
  dev_url: https://github.com/bacpop/mandrake

extra:
  recipe-maintainers:
    - johnlees
    - gtonkinhill
